use ark_ec::{pairing::Pairing, AffineRepr};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize, SerializationError};
use ark_std::{
    io::{Read, Write},
    vec::Vec,
};
use serde::{Deserialize, Serialize};

pub mod accumulator;
pub mod bbs_plus;
pub mod bound_check_legogroth16;
pub mod ped_comm;
pub mod r1cs_legogroth16;
pub mod saver;

pub use serialization::*;

/// Type of relation being proved and the public values for the relation
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(bound = "")]
pub enum Statement<E: Pairing, G: AffineRepr> {
    /// For proof of knowledge of BBS+ signature
    PoKBBSSignatureG1(bbs_plus::PoKBBSSignatureG1<E>),
    /// For proof of knowledge of committed elements in a Pedersen commitment
    PedersenCommitment(ped_comm::PedersenCommitment<G>),
    /// For proof of knowledge of an accumulator member and its corresponding witness
    AccumulatorMembership(accumulator::AccumulatorMembership<E>),
    /// For proof of knowledge of an accumulator non-member and its corresponding witness
    AccumulatorNonMembership(accumulator::AccumulatorNonMembership<E>),
    /// Used by prover to create proof of verifiable encryption using SAVER
    SaverProver(saver::SaverProver<E>),
    /// Used by verifier to verify proof of verifiable encryption using SAVER
    SaverVerifier(saver::SaverVerifier<E>),
    /// Used by prover to create proof that witness satisfies publicly known bounds inclusively (<=, >=) using LegoGroth16
    BoundCheckLegoGroth16Prover(bound_check_legogroth16::BoundCheckLegoGroth16Prover<E>),
    /// Used by verifier to verify proof that witness satisfies publicly known bounds inclusively (<=, >=) using LegoGroth16
    BoundCheckLegoGroth16Verifier(bound_check_legogroth16::BoundCheckLegoGroth16Verifier<E>),
    /// Used by prover to create proof that witness satisfies constraints given by an R1CS (generated by Circom), using LegoGroth16
    R1CSCircomProver(r1cs_legogroth16::R1CSCircomProver<E>),
    /// Used by verifier to verify proof that witness satisfies constraints given by an R1CS (generated by Circom), using LegoGroth16
    R1CSCircomVerifier(r1cs_legogroth16::R1CSCircomVerifier<E>),
}

/// A collection of statements
#[derive(
    Clone, Debug, PartialEq, CanonicalSerialize, CanonicalDeserialize, Serialize, Deserialize,
)]
#[serde(bound = "")]
pub struct Statements<E, G>(pub Vec<Statement<E, G>>)
where
    E: Pairing,
    G: AffineRepr;

impl<E, G> Statements<E, G>
where
    E: Pairing,
    G: AffineRepr,
{
    pub fn new() -> Self {
        Self(Vec::new())
    }

    pub fn add(&mut self, item: Statement<E, G>) -> usize {
        self.0.push(item);
        self.0.len() - 1
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    pub fn len(&self) -> usize {
        self.0.len()
    }
}

mod serialization {
    use super::*;
    use ark_serialize::{Compress, Valid, Validate};

    impl<E: Pairing, G: AffineRepr> Valid for Statement<E, G> {
        fn check(&self) -> Result<(), SerializationError> {
            match self {
                Self::PoKBBSSignatureG1(s) => s.check(),
                Self::AccumulatorMembership(s) => s.check(),
                Self::AccumulatorNonMembership(s) => s.check(),
                Self::PedersenCommitment(s) => s.check(),
                Self::SaverProver(s) => s.check(),
                Self::SaverVerifier(s) => s.check(),
                Self::BoundCheckLegoGroth16Prover(s) => s.check(),
                Self::BoundCheckLegoGroth16Verifier(s) => s.check(),
                Self::R1CSCircomProver(s) => s.check(),
                Self::R1CSCircomVerifier(s) => s.check(),
            }
        }
    }

    impl<E: Pairing, G: AffineRepr> CanonicalSerialize for Statement<E, G> {
        fn serialize_with_mode<W: Write>(
            &self,
            mut writer: W,
            compress: Compress,
        ) -> Result<(), SerializationError> {
            match self {
                Self::PoKBBSSignatureG1(s) => {
                    CanonicalSerialize::serialize_with_mode(&0u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
                Self::AccumulatorMembership(s) => {
                    CanonicalSerialize::serialize_with_mode(&1u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
                Self::AccumulatorNonMembership(s) => {
                    CanonicalSerialize::serialize_with_mode(&2u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
                Self::PedersenCommitment(s) => {
                    CanonicalSerialize::serialize_with_mode(&3u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
                Self::SaverProver(s) => {
                    CanonicalSerialize::serialize_with_mode(&4u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
                Self::SaverVerifier(s) => {
                    CanonicalSerialize::serialize_with_mode(&5u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
                Self::BoundCheckLegoGroth16Prover(s) => {
                    CanonicalSerialize::serialize_with_mode(&6u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
                Self::BoundCheckLegoGroth16Verifier(s) => {
                    CanonicalSerialize::serialize_with_mode(&7u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
                Self::R1CSCircomProver(s) => {
                    CanonicalSerialize::serialize_with_mode(&8u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
                Self::R1CSCircomVerifier(s) => {
                    CanonicalSerialize::serialize_with_mode(&9u8, &mut writer, compress)?;
                    CanonicalSerialize::serialize_with_mode(s, &mut writer, compress)
                }
            }
        }

        fn serialized_size(&self, compress: Compress) -> usize {
            match self {
                Self::PoKBBSSignatureG1(s) => {
                    0u8.serialized_size(compress) + s.serialized_size(compress)
                }
                Self::AccumulatorMembership(s) => {
                    1u8.serialized_size(compress) + s.serialized_size(compress)
                }
                Self::AccumulatorNonMembership(s) => {
                    2u8.serialized_size(compress) + s.serialized_size(compress)
                }
                Self::PedersenCommitment(s) => {
                    3u8.serialized_size(compress) + s.serialized_size(compress)
                }
                Self::SaverProver(s) => 4u8.serialized_size(compress) + s.serialized_size(compress),
                Self::SaverVerifier(s) => {
                    5u8.serialized_size(compress) + s.serialized_size(compress)
                }
                Self::BoundCheckLegoGroth16Prover(s) => {
                    6u8.serialized_size(compress) + s.serialized_size(compress)
                }
                Self::BoundCheckLegoGroth16Verifier(s) => {
                    7u8.serialized_size(compress) + s.serialized_size(compress)
                }
                Self::R1CSCircomProver(s) => {
                    8u8.serialized_size(compress) + s.serialized_size(compress)
                }
                Self::R1CSCircomVerifier(s) => {
                    97u8.serialized_size(compress) + s.serialized_size(compress)
                }
            }
        }
    }

    impl<E: Pairing, G: AffineRepr> CanonicalDeserialize for Statement<E, G> {
        fn deserialize_with_mode<R: Read>(
            mut reader: R,
            compress: Compress,
            validate: Validate,
        ) -> Result<Self, SerializationError> {
            let t: u8 =
                CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?;
            match t {
                0u8 => Ok(Self::PoKBBSSignatureG1(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                1u8 => Ok(Self::AccumulatorMembership(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                2u8 => Ok(Self::AccumulatorNonMembership(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                3u8 => Ok(Self::PedersenCommitment(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                4u8 => Ok(Self::SaverProver(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                5u8 => Ok(Self::SaverVerifier(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                6u8 => Ok(Self::BoundCheckLegoGroth16Prover(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                7u8 => Ok(Self::BoundCheckLegoGroth16Verifier(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                8u8 => Ok(Self::R1CSCircomProver(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                9u8 => Ok(Self::R1CSCircomVerifier(
                    CanonicalDeserialize::deserialize_with_mode(&mut reader, compress, validate)?,
                )),
                _ => Err(SerializationError::InvalidData),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_bls12_381::Bls12_381;
    use ark_bls12_381::{fr::Fr, g1::G1Projective as G1Proj};
    use ark_ec::{CurveGroup, VariableBaseMSM};
    use ark_std::{
        collections::BTreeMap,
        rand::{rngs::StdRng, SeedableRng},
        UniformRand,
    };
    use test_utils::test_serialization;
    use test_utils::{
        accumulators::{setup_positive_accum, setup_universal_accum},
        bbs_plus::sig_setup,
    };
    use vb_accumulator::prelude::{Accumulator, MembershipProvingKey, NonMembershipProvingKey};

    #[test]
    fn statement_serialization_deserialization() {
        let mut rng = StdRng::seed_from_u64(0u64);
        let (_, params_1, keypair_1, _) = sig_setup(&mut rng, 5);
        let (pos_params, pos_keypair, pos_accumulator, _) = setup_positive_accum(&mut rng);
        let (uni_params, uni_keypair, uni_accumulator, _, _) = setup_universal_accum(&mut rng, 100);
        let mem_prk =
            MembershipProvingKey::<<Bls12_381 as Pairing>::G1Affine>::generate_using_rng(&mut rng);
        let non_mem_prk =
            NonMembershipProvingKey::<<Bls12_381 as Pairing>::G1Affine>::generate_using_rng(
                &mut rng,
            );

        let mut statements: Statements<Bls12_381, <Bls12_381 as Pairing>::G1Affine> =
            Statements::new();

        let stmt_1 = bbs_plus::PoKBBSSignatureG1::new_statement_from_params(
            params_1.clone(),
            keypair_1.public_key.clone(),
            BTreeMap::new(),
        );
        test_serialization!(Statement<Bls12_381, <Bls12_381 as Pairing>::G1Affine>, stmt_1);

        statements.add(stmt_1);
        test_serialization!(Statements<Bls12_381, <Bls12_381 as Pairing>::G1Affine>, statements);

        let stmt_2 = accumulator::AccumulatorMembership::new_statement_from_params::<
            <Bls12_381 as Pairing>::G1Affine,
        >(
            pos_params.clone(),
            pos_keypair.public_key.clone(),
            mem_prk.clone(),
            pos_accumulator.value().clone(),
        );
        test_serialization!(Statement<Bls12_381, <Bls12_381 as Pairing>::G1Affine>, stmt_2);

        statements.add(stmt_2);
        test_serialization!(Statements<Bls12_381, <Bls12_381 as Pairing>::G1Affine>, statements);

        let stmt_3 = accumulator::AccumulatorNonMembership::new_statement_from_params::<
            <Bls12_381 as Pairing>::G1Affine,
        >(
            uni_params.clone(),
            uni_keypair.public_key.clone(),
            non_mem_prk.clone(),
            uni_accumulator.value().clone(),
        );
        test_serialization!(Statement<Bls12_381, <Bls12_381 as Pairing>::G1Affine>, stmt_3);

        statements.add(stmt_3);
        test_serialization!(Statements<Bls12_381, <Bls12_381 as Pairing>::G1Affine>, statements);

        let bases = (0..5)
            .map(|_| G1Proj::rand(&mut rng).into_affine())
            .collect::<Vec<_>>();
        let scalars = (0..5).map(|_| Fr::rand(&mut rng)).collect::<Vec<_>>();
        let commitment = G1Proj::msm_unchecked(&bases, &scalars).into_affine();
        let stmt_4 = ped_comm::PedersenCommitment::new_statement_from_params(bases, commitment);
        test_serialization!(Statement<Bls12_381, <Bls12_381 as Pairing>::G1Affine>, stmt_4);

        statements.add(stmt_4);
        test_serialization!(Statements<Bls12_381, <Bls12_381 as Pairing>::G1Affine>, statements);
    }
}
